/*
 * Copyright (c) 2021, Matthew Olsson <matthewcolsson@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <LibGfx/AAPainter.h>

#define AAPAINTER_DEBUG 0

namespace Gfx {

AAPainter::AAPainter(Gfx::Bitmap* bitmap)
    : m_target(bitmap)
{
    m_state_stack.append({ {}, bitmap->physical_rect() });
}

AAPainter::~AAPainter()
{
}

void AAPainter::draw_line(PainterPoint p0, PainterPoint p1, Color color, float thickness)
{
    if (p0 == p1)
        return;

    VERIFY(line_style() == LineStyle::Solid);
    VERIFY(thickness >= 1.0f);

    p0 = convert_to_physical(p0);
    p1 = convert_to_physical(p1);

    dbgln_if(AAPAINTER_DEBUG, "[draw_line] p0={} p1={} thickness={} clip_rect={}", p0, p1, thickness, clip_rect());

    bool steep = abs(p1.y() - p0.y()) > abs(p1.x() - p0.x());

    if ((steep && p0.y() > p1.y()) || (!steep && p0.x() > p1.x()))
        swap(p0, p1);

    int dx = p1.x() - p0.x();
    int dy = p1.y() - p0.y();

    // By default, lines generated by this method look a bit too thick.
    // Taking half a pixel of the thickness seems to be about right.
    thickness -= 0.5f;
    float half_thickness = thickness / 2.0f;

    float slope = static_cast<float>(dy) / static_cast<float>(dx);

    if (steep) {
        slope = 1.0f / slope;
        auto current_x = static_cast<float>(p0.x());

        half_thickness *= scale().x();

        for (int y = p0.y(); y <= p1.y(); y++) {
            if (!clip_rect().contains_vertically(y))
                continue;

            auto x0 = static_cast<int>(floor(current_x - half_thickness));
            auto x1 = static_cast<int>(ceil(current_x + half_thickness));

            for (int x = x0; x <= x1; x++) {
                if (!clip_rect().contains_horizontally(x))
                    continue;

                float error = fabs(current_x - static_cast<float>(x));

                if (error <= half_thickness) {
                    // This pixel is within the full bounds of the line, and
                    // should not be aliased at all
                    m_target->set_pixel(x, y, color);
                } else {
                    error -= half_thickness;
                    VERIFY(error <= 1);
                    auto new_color = m_target->get_pixel(x, y).blend(color.with_alpha(static_cast<u8>(255.0f * (1.0f - error))));
                    m_target->set_pixel(x, y, new_color);
                }
            }

            current_x += slope;
        }
    } else {
        auto current_y = static_cast<float>(p0.y());

        half_thickness *= scale().y();

        for (int x = p0.x(); x <= p1.x(); x++) {
            auto y0 = static_cast<int>(floor(current_y - half_thickness));
            auto y1 = static_cast<int>(ceil(current_y + half_thickness));

            for (int y = y0; y <= y1; y++) {
                float error = fabs(current_y - static_cast<float>(y));

                if (error <= half_thickness) {
                    // This pixel is within the full bounds of the line, and
                    // should not be aliased at all
                    m_target->set_pixel(x, y, color);
                } else {
                    error -= half_thickness;
                    VERIFY(error <= 1);
                    auto new_color = m_target->get_pixel(x, y).blend(color.with_alpha(static_cast<u8>(255.0f * (1.0f - error))));
                    m_target->set_pixel(x, y, new_color);
                }
            }

            current_y += slope;
        }
    }
}

ALWAYS_INLINE static float fpart(float n) {
    return n - floor(n);
}

ALWAYS_INLINE static float rfpart(float n) {
    return n - fpart(n);
}

void AAPainter::draw_path([[maybe_unused]] const Gfx::Path& path, [[maybe_unused]] Color color)
{
}

}
